#
# Module manifest for module 'PSScriptInfo'
#
# Generated by: Hannes Palmquist
#
# Generated on: 2022-11-14
#

@{
    RootModule           = 'PSScriptInfo.psm1'
    ModuleVersion        = '0.0.1'
    CompatiblePSEditions = @('Desktop', 'Core')
    PowerShellVersion    = '5.1'
    GUID                 = '85a70594-7a0d-4606-a1c2-2eda65cb54a1'
    Author               = 'Hannes Palmquist'
    CompanyName          = 'GetPS'
    Copyright            = '(c) Hannes Palmquist. All rights reserved.'
    Description          = 'Tools for generating and updating psscriptinfo on scripts'
    RequiredModules      = @()
    FunctionsToExport    = '*'
    CmdletsToExport      = '*'
    VariablesToExport    = '*'
    AliasesToExport      = '*'
    PrivateData          = @{
        PSData = @{
            Prerelease               = ''
            Tags                     = @('PSEdition_Desktop', 'PSEdition_Core', 'Windows', 'Linux', 'MacOS')
            LicenseUri               = 'https://github.com/hanpq/PSScriptInfo/blob/main/LICENSE'
            ProjectUri               = 'https://getps.dev/modules/PSScriptInfo/getstarted'
            IconUri                  = ''
            ReleaseNotes             = ''
            RequireLicenseAcceptance = $false
        }
    }
}


